include ~/.config/omarchy/current/theme/kitty.conf

enable_audio_bell no

# Font
font_family TerminessTTF Nerd Font
italic_font auto
bold_italic_font auto
font_size 11.0

confirm_os_window_close 0

# Cursor
cursor #8fee96

term xterm-256color
background_opacity 0.8
background_blur 1

map super+v paste_from_clipboard
enable_bracketed_paste yes

allow_remote_control yes
clipboard_control write-clipboard write-primary
